#security.oauth2.client:
#    clientId: acme
#    clientSecret: acmesecret
#    authorized-grant-types: refresh_token,password
#    scope: openid
    
server:
    port: 9999
    contextPath: /uaa
    
security:
    user.password: password
    
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    
    
# enabling h2 webcosole. 
# http://localhost:9999/uaa/h2-console
spring.h2.console.enabled: true
