spring.application.name: resource001

server:
  port: 8070

management.security.enabled: false

security:
    oauth2.resource.userInfoUri: http://localhost:9999/uaa/user
    user.password: password
        
#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG