

server:
  port: 8080
  
security:
  user:
    password: password

# client details are configured per bean
oauth2:
    resource:
        userInfoUri: http://localhost:9999/uaa/user
        
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
